# Imports

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

# Data Loading

In [5]:
df=pd.read_csv('/content/train.csv')
df

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  ...  subject          Activity
0              0.288585          -0.020294  ...        1          STANDING
1              0.278419          -0.016411  ...        1          STANDING
2              0.279653          -0.019467  ...        1          STANDING
3              0.279174          -0.026201  ...        1          STANDING
4              0.276629          -0.016570  ...        1          STANDING
...                 ...                ...  ...      ...               ...
7347           0.299665          -0.057193  ...       30  WALKING_UPSTAIRS
7348           0.273853          -0.007749  ...       30  WALKING_UPSTAIRS
7349           0.273387          -0.017011  ...       30  WALKING_UPSTAIRS
7350           0.289654          -0.018843  ...       30  WALKING_UPSTAIRS
7351           0.351503          -0.012423  ...       30  WALKING_UPSTAIRS

[7352 rows x 563 columns]

# Data Processing

In [6]:
df.select_dtypes(include='object')

Activity
0             STANDING
1             STANDING
2             STANDING
3             STANDING
4             STANDING
...                ...
7347  WALKING_UPSTAIRS
7348  WALKING_UPSTAIRS
7349  WALKING_UPSTAIRS
7350  WALKING_UPSTAIRS
7351  WALKING_UPSTAIRS

[7352 rows x 1 columns]

In [7]:
df['Activity'].unique()

array(['STANDING', 'SITTING', 'LAYING', 'WALKING', 'WALKING_DOWNSTAIRS',
       'WALKING_UPSTAIRS'], dtype=object)

In [8]:
df['Activity']=df['Activity'].map({'STANDING':0,'SITTING':1,
                                   'LAYING':2,'WALKING':3,
                                   'WALKING_UPSTAIRS':4,'WALKING_DOWNSTAIRS':5})

In [9]:
df.isnull().sum()

tBodyAcc-mean()-X       0
tBodyAcc-mean()-Y       0
tBodyAcc-mean()-Z       0
tBodyAcc-std()-X        0
tBodyAcc-std()-Y        0
                       ..
angle(X,gravityMean)    0
angle(Y,gravityMean)    0
angle(Z,gravityMean)    0
subject                 0
Activity                0
Length: 563, dtype: int64

In [10]:
sum(df.isnull().sum())

0

# Model Training

In [11]:
y=df['Activity']
x=df.drop(['Activity'],axis=1)

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

**Employed SGDClassfier as it is highly suited for large datasets. Calculated the accuracy for new dataset as well**

In [15]:
sgd=SGDClassifier(loss='hinge',penalty='l2',max_iter=1000,random_state=42)
sgd.fit(x_train,y_train)

SGDClassifier(random_state=42)

In [16]:
y_pred=sgd.predict(x_train)
score=accuracy_score(y_train,y_pred)
cm=confusion_matrix(y_train,y_pred)
print(score)
print(cm)
print(classification_report(y_train,y_pred))

0.9799844539448115
[[868  95   0   0   0   0]
 [  5 895   0   0   0   0]
 [  0   0 979   0   0   0]
 [  0   0   0 860   0   0]
 [  0   0   0   2 766   1]
 [  0   0   0   0   0 675]]
              precision    recall  f1-score   support

           0       0.99      0.90      0.95       963
           1       0.90      0.99      0.95       900
           2       1.00      1.00      1.00       979
           3       1.00      1.00      1.00       860
           4       1.00      1.00      1.00       769
           5       1.00      1.00      1.00       675

    accuracy                           0.98      5146
   macro avg       0.98      0.98      0.98      5146
weighted avg       0.98      0.98      0.98      5146



In [17]:
y_predict=sgd.predict(x_test)
score=accuracy_score(y_test,y_predict)
cm=confusion_matrix(y_test,y_predict)
print(score)
print(cm)
print(classification_report(y_test,y_predict))

0.970081595648232
[[370  41   0   0   0   0]
 [  6 380   0   0   0   0]
 [  0   0 427   0   0   1]
 [  0   0   0 362   4   0]
 [  0   0   0   2 297   5]
 [  0   0   0   5   2 304]]
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       411
           1       0.90      0.98      0.94       386
           2       1.00      1.00      1.00       428
           3       0.98      0.99      0.99       366
           4       0.98      0.98      0.98       304
           5       0.98      0.98      0.98       311

    accuracy                           0.97      2206
   macro avg       0.97      0.97      0.97      2206
weighted avg       0.97      0.97      0.97      2206



In [39]:
d={0:'STANDING',
   1:'SITTING',
   2:'LAYING',
   3:'WALKING',
   4:'WALKING_UPSTAIRS',
   5:'WALKING_DOWNSTAIRS'}

In [57]:
import numpy as np
random_sample = np.random.uniform(-1,1,(1, 562))
predicted_target = sgd.predict(random_sample)
print("Predicted target for the random sample:", d[predicted_target[0]])


Predicted target for the random sample: LAYING


**New Dataset**

In [58]:
test=pd.read_csv('/content/test.csv')
xt=test.drop(['Activity'],axis=1)
yt=test['Activity']

In [61]:
y_pred_test = sgd.predict(xt)
predicted_activities = [d[pred] for pred in y_pred_test]
accuracy_score(yt,predicted_activities)

0.9548693586698337

**Use SVC--> linear model**

In [53]:
svc=SVC(kernel='linear')
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [25]:
y_pred=svc.predict(x_train)
score=accuracy_score(y_train,y_pred)
cm=confusion_matrix(y_train,y_pred)
print(score)
print(cm)
print(classification_report(y_train,y_pred))

0.9943645549941702
[[947  16   0   0   0   0]
 [ 13 887   0   0   0   0]
 [  0   0 979   0   0   0]
 [  0   0   0 860   0   0]
 [  0   0   0   0 769   0]
 [  0   0   0   0   0 675]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98       963
           1       0.98      0.99      0.98       900
           2       1.00      1.00      1.00       979
           3       1.00      1.00      1.00       860
           4       1.00      1.00      1.00       769
           5       1.00      1.00      1.00       675

    accuracy                           0.99      5146
   macro avg       0.99      0.99      0.99      5146
weighted avg       0.99      0.99      0.99      5146



In [26]:
y_predict=svc.predict(x_test)
score=accuracy_score(y_test,y_predict)
cm=confusion_matrix(y_test,y_predict)
print(score)
print(cm)
print(classification_report(y_test,y_predict))

0.9845874886672711
[[398  13   0   0   0   0]
 [ 17 369   0   0   0   0]
 [  0   0 428   0   0   0]
 [  0   0   0 365   1   0]
 [  0   0   0   0 302   2]
 [  0   0   0   1   0 310]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.96       411
           1       0.97      0.96      0.96       386
           2       1.00      1.00      1.00       428
           3       1.00      1.00      1.00       366
           4       1.00      0.99      1.00       304
           5       0.99      1.00      1.00       311

    accuracy                           0.98      2206
   macro avg       0.99      0.99      0.99      2206
weighted avg       0.98      0.98      0.98      2206



**Use SVC--> RBF model**

In [27]:
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)

SVC()

In [28]:
y_pred=svc.predict(x_train)
score=accuracy_score(y_train,y_pred)
cm=confusion_matrix(y_train,y_pred)
print(score)
print(cm)
print(classification_report(y_train,y_pred))

0.9479207151185387
[[876  87   0   0   0   0]
 [140 747  12   0   1   0]
 [  0   0 979   0   0   0]
 [  0   0   0 855   5   0]
 [  0   0   0   5 762   2]
 [  0   0   0   3  13 659]]
              precision    recall  f1-score   support

           0       0.86      0.91      0.89       963
           1       0.90      0.83      0.86       900
           2       0.99      1.00      0.99       979
           3       0.99      0.99      0.99       860
           4       0.98      0.99      0.98       769
           5       1.00      0.98      0.99       675

    accuracy                           0.95      5146
   macro avg       0.95      0.95      0.95      5146
weighted avg       0.95      0.95      0.95      5146



In [29]:
y_predict=svc.predict(x_test)
score=accuracy_score(y_test,y_predict)
cm=confusion_matrix(y_test,y_predict)
print(score)
print(cm)
print(classification_report(y_test,y_predict))

0.9492293744333635
[[383  28   0   0   0   0]
 [ 60 324   2   0   0   0]
 [  0   0 428   0   0   0]
 [  0   0   0 361   5   0]
 [  0   0   0   4 298   2]
 [  0   0   0   5   6 300]]
              precision    recall  f1-score   support

           0       0.86      0.93      0.90       411
           1       0.92      0.84      0.88       386
           2       1.00      1.00      1.00       428
           3       0.98      0.99      0.98       366
           4       0.96      0.98      0.97       304
           5       0.99      0.96      0.98       311

    accuracy                           0.95      2206
   macro avg       0.95      0.95      0.95      2206
weighted avg       0.95      0.95      0.95      2206



**Use SVC--> polynomial mode**

In [30]:
svc=SVC(kernel='poly')
svc.fit(x_train,y_train)

SVC(kernel='poly')

In [31]:
y_pred=svc.predict(x_train)
score=accuracy_score(y_train,y_pred)
cm=confusion_matrix(y_train,y_pred)
print(score)
print(cm)
print(classification_report(y_train,y_pred))

0.9500582977069568
[[912  51   0   0   0   0]
 [ 84 811   4   0   1   0]
 [  0   0 976   0   3   0]
 [  0   0   0 852   8   0]
 [  0   0   0  40 725   4]
 [  0   0   0  54   8 613]]
              precision    recall  f1-score   support

           0       0.92      0.95      0.93       963
           1       0.94      0.90      0.92       900
           2       1.00      1.00      1.00       979
           3       0.90      0.99      0.94       860
           4       0.97      0.94      0.96       769
           5       0.99      0.91      0.95       675

    accuracy                           0.95      5146
   macro avg       0.95      0.95      0.95      5146
weighted avg       0.95      0.95      0.95      5146



In [32]:
y_predict=svc.predict(x_test)
score=accuracy_score(y_test,y_predict)
cm=confusion_matrix(y_test,y_predict)
print(score)
print(cm)
print(classification_report(y_test,y_predict))

0.9406165004533091
[[389  22   0   0   0   0]
 [ 43 343   0   0   0   0]
 [  0   0 427   0   1   0]
 [  0   0   0 360   6   0]
 [  0   0   0  16 288   0]
 [  0   0   0  36   7 268]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.92       411
           1       0.94      0.89      0.91       386
           2       1.00      1.00      1.00       428
           3       0.87      0.98      0.93       366
           4       0.95      0.95      0.95       304
           5       1.00      0.86      0.93       311

    accuracy                           0.94      2206
   macro avg       0.94      0.94      0.94      2206
weighted avg       0.94      0.94      0.94      2206



**Use SVC--> sigmoid mode**

In [33]:
svc=SVC(kernel='sigmoid')
svc.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [34]:
y_pred=svc.predict(x_train)
score=accuracy_score(y_train,y_pred)
cm=confusion_matrix(y_train,y_pred)
print(score)
print(cm)
print(classification_report(y_train,y_pred))

0.35697629226583755
[[229 160 306   0 268   0]
 [140 200 296   2 262   0]
 [  2  99 618  36 224   0]
 [ 13   0 243 245 359   0]
 [  4   0 248  98 416   3]
 [ 20   0  89 149 288 129]]
              precision    recall  f1-score   support

           0       0.56      0.24      0.33       963
           1       0.44      0.22      0.29       900
           2       0.34      0.63      0.44       979
           3       0.46      0.28      0.35       860
           4       0.23      0.54      0.32       769
           5       0.98      0.19      0.32       675

    accuracy                           0.36      5146
   macro avg       0.50      0.35      0.34      5146
weighted avg       0.49      0.36      0.35      5146



In [35]:
y_predict=svc.predict(x_test)
score=accuracy_score(y_test,y_predict)
cm=confusion_matrix(y_test,y_predict)
print(score)
print(cm)
print(classification_report(y_test,y_predict))

0.34950135992747056
[[105  72 109   0 125   0]
 [ 73  81 133   2  97   0]
 [  0  54 260  20  94   0]
 [  6   0  95 105 160   0]
 [  0   0  94  42 168   0]
 [ 20   0  40  72 127  52]]
              precision    recall  f1-score   support

           0       0.51      0.26      0.34       411
           1       0.39      0.21      0.27       386
           2       0.36      0.61      0.45       428
           3       0.44      0.29      0.35       366
           4       0.22      0.55      0.31       304
           5       1.00      0.17      0.29       311

    accuracy                           0.35      2206
   macro avg       0.49      0.35      0.33      2206
weighted avg       0.48      0.35      0.34      2206

